package model.states.warehouse;

import java.util.List;

public interface WarehouseLevels {
     List<List<String>> TEMPLATES = List.of(
            List.of(
                    "HHH   H ",
                    "  H * H ",
                    "    *HHH",
                    " HHH * H",
                    " H *   H",
                    "DH     H",
                    "@H ! HHH",
                    " HHH H  ",
                    "     H  "),
            List.of(
                    "*HHHHHH*",
                    "HHH   H*",
                    "H ! H HH",
                    "H H   @D",
                    "H    H H",
                    "HH H   H",
                    "HH   HHH",
                    "*HHHHHH*",
                    "  H**H  "),
            List.of(
                    "    HHHH",
                    "HHHHH  H",
                    "H   !  H",
                    "D@  H  H",
                    "HH HH HH",
                    "H      H",
                    "H  H   H",
                    "H  HHHHH",
                    "*HHH    "),
            List.of(
                    "HHHHH   ",
                    "H   HHHH",
                    "    H  H",
                    "HH     H",
                    "HH HHH H",
                    " * H H H",
                    " !*H H H",
                    "@  H H H",
                    "HHHH HDH"),
            List.of(
                    " HHHHHHH",
                    " H     H",
                    " H * @ H",
                    "HHHH H H",
                    " !     H",
                    "  H*HH H",
                    "  *  H  ",
                    "        ",
                    "DHHHHHHH"),
            List.of(
                    "HHHHHHHH",
                    "H  * HH ",
                    "D *  H  ",
                    "HH * H* ",
                    "HH* HHH ",
                    " @! H   ",
                    "H   H   ",
                    "HHHHH * ",
                    "   *  HH"),
            List.of(
                    "   HHHH ",
                    "*HHH  HH",
                    " H *@  D",
                    " H H   H",
                    " H H!HHH",
                    " H H   H",
                    "*H   * H",
                    " HH *  H",
                    "  H  HHH"),
            List.of(
                    "HHH   @H",
                    "H   !  H",
                    "H HH HHH",
                    "H  H*  H",
                    "H **   H",
                    "H   * HH",
                    "H HHHHH ",
                    "H H     ",
                    "HDH    *"),
            List.of(
                    "  HDHH  ",
                    " HH  H *",
                    " H   H  ",
                    "HH * H  ",
                    "H ! *HH ",
                    "H H*  H ",
                    "H H * H ",
                    "H     H ",
                    "HHH@HHH "),
            List.of(
                    "HHDH    ",
                    "H  HHH  ",
                    "H    HHH",
                    "H ****@H",
                    "HH   H H",
                    " H H   H",
                    " H   !HH",
                    " HHH  H ",
                    "   HHHH "
            )
    );
}
