package rulebook;

import rulebook.chapters.*;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

public class GenerateRulebook {

    public static final String PATH_BASE = "out/rulebook";
    public static final String DO_NOT_EDIT_DISCLAIMER = "<!-- This file has been generated by GenerateRulebook.java, DO NOT edit manually!-->\n\n";

    public static void main(String[] args) {
        List<RulebookChapter> chapters = List.of(
                new CharactersChapter(),
                new RacesChapter(),
                new ClassesChapter(),
                new SkillsChapter(),
                new AbilitiesChapter());
        for (RulebookChapter chap : chapters) {
            try {
                BufferedWriter writer = makeWriter(chap.getName());
                chap.generate(writer);
                writer.close();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    private static BufferedWriter makeWriter(String chapterTitle) throws IOException {
        BufferedWriter writer = null;
        writer = new BufferedWriter(new FileWriter(makeFile(chapterTitle.toLowerCase())));
        writer.write(DO_NOT_EDIT_DISCLAIMER);
        writer.write("## " + chapterTitle + "\n\n");
        return writer;
    }

    private static File makeFile(String chapterName) {
        File outFile = new File(PATH_BASE + "/chapters/" + chapterName + ".md");
        if (!outFile.exists()) {
            try {
                outFile.createNewFile();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        return outFile;
    }
}
