package rulebook;

import model.classes.*;
import model.items.Equipment;
import model.items.Item;
import util.MyStrings;
import view.sprites.Sprite;
import view.widget.DetailedClassNameStrategy;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import java.util.Arrays;
import java.util.List;
import java.util.ArrayList;

public class GenerateRulebook {

    private static final String PATH_BASE = "out/rulebook";
    private static final String DO_NOT_EDIT_DISCLAIMER = "<!-- This file has been generated by GenerateRulebook.java, DO NOT edit manually!-->\n\n";

    public static void main(String[] args) {
        generateClassesChapter();
    }

    private static void generateClassesChapter() {
        List<CharacterClass> classes = new ArrayList<>(Arrays.stream(Classes.allClasses).toList());
        classes.removeIf(cc -> cc instanceof NoClass);

        for (CharacterClass cc : classes) {
            try {
                Sprite spr = cc.getIconSprite();
                BufferedImage img = spr.getImage();
                File outFile = new File(PATH_BASE + "/images/" + cc.getShortName().toLowerCase() + "_class_icon.png");
                if (!outFile.exists()) {
                    outFile.createNewFile();
                }
                ImageIO.write(img, "png", outFile);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }

        File outFile = new File(PATH_BASE + "/chapters/classes.md");
        if (!outFile.exists()) {
            try {
                outFile.createNewFile();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }

        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter(outFile));
            writer.write(DO_NOT_EDIT_DISCLAIMER);
            writer.write("## Classes\n\n");
            writer.write("The following classes are available at the start of the game.\n\n");
            writer.write("| Class | Short Name | Description |\n");
            writer.write("|-------|------------|-------------|\n");
            for (CharacterClass cc : classes) {
                writer.write("| " + cc.getFullName() + " | " + cc.getShortName() + " | " + DetailedClassNameStrategy.getClassShortDescription(cc) + "|\n");
            }
            writer.newLine();
            writer.newLine();
            writer.write("### Class Template (Short Name)\n");
            writer.write("<i>Class description</i>\n");
            writer.write("<p><b>Health Points:</b> Number of Health Point your character starts with, modified by your race.<br/>\n");
            writer.write("<b>Speed:</b> Your character's speed, modified by race.<br/>\n");
            writer.write("<b>Armor Class:</b> Determines if your character can equip Heavy armor or is limited to Light armor.<br/>\n");
            writer.write("<b>Skill Weights</b> Determines your character's Skill progression. " +
                    "In general, a higher weight means your character will progress more quickly in that skill.<br/>\n");
            writer.write("<b>Default Gear</b> The gear your character starts the game with.<br/>\n");
            writer.write("<b>Starting Items</b> Your character may start with two of the items from " +
                    "this list. If you select a weapon or piece of clothing from this list it replaces " +
                    "any you would receive from your default gear.<br/>\n</p>");


            writer.newLine();
            writer.newLine();
            for (CharacterClass cc : classes) {
                writer.write("### " + cc.getFullName() + " (" + cc.getShortName() + ")\n");
                writer.write("<p align=\"center\"><img src=\"../images/" + cc.getShortName().toLowerCase() + "_class_icon.png\" alt=\"\"/></p>\n");
                writer.newLine();
                writer.write(cc.getDescription());
                writer.newLine();
                writer.newLine();
                writer.write("<p><b>Health Points:</b> " + cc.getHP() + "<br/>\n");
                writer.write("<b>Speed:</b> " + cc.getSpeed() + "<br/>\n");
                writer.write("<b>Armor Class:</b> " + (cc.canUseHeavyArmor() ? "HEAVY" : "LIGHT") + "<br/>\n");
                int align = Classes.ALIGNMENT.getOrDefault(cc.id(), 0);
                writer.write("<b>Alignment: </b>" + MyStrings.withPlus(align) + "<br/></p>\n");
                writer.newLine();

                writer.write("|      Skill      | Weight |      Skill      | Weight |\n");
                writer.write("|-----------------|--------|-----------------|--------|");
                int count = 0;
                for (Skill s : cc.getSkills()) {
                    if (count % 2 == 0) {
                        writer.write("\n|");
                    }
                    writer.write( String.format(" %-15s | %6s |", s.getName(), cc.getWeightForSkill(s).asString()));
                    count++;
                }
                if (count % 2 == 1) {
                    writer.write("                 |        |\n");
                }
                writer.newLine();
                writer.newLine();
                Equipment eq = cc.getDefaultEquipment();
                writer.write("<p><b>Default Gear: </b>" + eq.getWeapon().getName() + ", " + eq.getClothing().getName() +
                        (eq.getAccessory() != null ? (", " + eq.getAccessory().getName()) : "") + "<br/>\n\n");
                writer.write("<b>Starting Items:</b>\n");
                for (Item it : cc.getStartingItems()) {
                    writer.write("* " + it.getName() + "\n");
                }
                writer.write("</p>\n\n");
            }
            writer.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
