package rulebook;

import model.classes.CharacterClass;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class GenerateRulebook {

    public static final String PATH_BASE = "out/rulebook";
    public static final String DO_NOT_EDIT_DISCLAIMER = "<!-- This file has been generated by GenerateRulebook.java, DO NOT edit manually!-->\n\n";

    public static void main(String[] args) {
        try {
            BufferedWriter writer = makeWriter("Characters");
            CharactersChapter.generate(writer);
            writer.close();

            writer = makeWriter("Races");
            RacesChapter.generate(writer);
            writer.close();

            writer = makeWriter("Classes");
            ClassesChapter.generate(writer);
            writer.close();

            writer = makeWriter("Skills");
            SkillsChapter.generate(writer);
            writer.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static BufferedWriter makeWriter(String chapterTitle) throws IOException {
        BufferedWriter writer = null;
        writer = new BufferedWriter(new FileWriter(makeFile(chapterTitle.toLowerCase())));
        writer.write(DO_NOT_EDIT_DISCLAIMER);
        writer.write("## " + chapterTitle + "\n\n");
        return writer;
    }

    private static File makeFile(String chapterName) {
        File outFile = new File(PATH_BASE + "/chapters/" + chapterName + ".md");
        if (!outFile.exists()) {
            try {
                outFile.createNewFile();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        return outFile;
    }
}
